<?php

/**
 * @file
 * Installation file for ucb_openberkeley module.
 */

/**
 * DRUPALOPS-153: Permission changes for admin role prevent.
 */
function ucb_openberkeley_update_7001() {
  $builder = user_role_load_by_name('builder')->rid;
  $permissions = array(
    'administer users' => FALSE,
    'administer cas create' => TRUE, 
  );
  if (isset($builder)) {
    user_role_change_permissions($builder, $permissions);
  }
  return t('Adjusted builder permissions for admin role prevent.');
}
