<?php
/**
 * UCB Open Berkeley customizations
 */

//TODO: Revisit this after upgrading to Panopoly 7.x-1.0-rc3

/**
 * Implementation of hook_form_alter
 *
 */
function ucb_openberkeley_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case "views_form_control_users_page_1":
      if (!isset($form['add_roles']) || (!isset($form['remove_roles']))) {
        break;
      }
      $admin_rid = variable_get('user_admin_role');
      $roles = user_roles();
      $admin_rolename = NULL;
      if ((!is_array($roles)) || (!array_key_exists($admin_rid, $roles))) {
        drupal_set_message("Roles may be misconfigured. Possible security implications. Ask your administrator to check on this.", "warning");
      }
      else {
       $admin_rolename = $roles[$admin_rid];
      }

      while (list($k, $v)  = each($form['add_roles']['#options'])) {
        if ($v == $admin_rolename) {
          unset($form['add_roles']['#options'][$k]);
        }
      }
      while (list($k, $v)  = each($form['remove_roles']['#options'])) {
        if ($v == $admin_rolename) {
          unset($form['remove_roles']['#options'][$k]);
        }
      }
      break;
  }
}

/**
 * Implementation of hook_module_implements_alter()
 * Change order of hook execution without needing to alter module weight
 * See http://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_module_implements_alter/7
 */

function ucb_openberkeley_module_implements_alter(&$implementations, $hook) {
  //Any change here requires caches to be cleared.
  if ($hook == 'wysiwyg_editor_settings_alter') {
    $first = $implementations['panopoly_wysiwyg'];
    unset($implementations['panopoly_wysiwyg']);

    $second = $implementations['ucb_openberkeley'];
    unset($implementations['ucb_openberkeley']);

    //Call wysiwyg_editor_settings_alter on panopoly_wysiwyg then ucb_openberkeley
    $implementations['panopoly_wysiwyg'] = $first;
    $implementations['ucb_openberkeley'] = $second;
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter()
 * See wysiwyg.api.php (wysiwyg module)
 */


//Override default order for the WYSIWYG -  see panopoly_wysiwyg.module for other defaults
function ucb_openberkeley_wysiwyg_editor_settings_alter(&$settings, $context) {
  //See hook_module_implements_alter() and clear caches if necessary

  if ($context['editor']['name'] == 'tinymce') {

    // Panopoly_wysiwyg.module has already processed $settings['theme_advanced_buttons1'], so we need to recreate original enabled list; pdw_toggle and formatselect become pdw_toggleformatselect so need workaround to include (see below)
    $enabled_buttons = explode(',', ($settings['theme_advanced_buttons1'] . $settings['theme_advanced_buttons2'] . $settings['theme_advanced_buttons3']));

    //First row buttons
    //Move linkit button to link section if linkit exists
    if (module_exists('linkit')) {

      //Need to include 'strikethrough' and 'captionfilter' because panopoly_wysiwyg.module lists in its
      //default buttons. Will be unset if not enabled.
      $first_row_buttons = array('bold', 'italic', 'strikethrough', '|', 'bullist', 'numlist', 'blockquote', '|', 'justifyleft', 'justifycenter','justifyright','|','link', 'linkit', 'unlink', 'break', '|', 'fullscreen', 'spellchecker', 'media', 'captionfilter', 'pdw_toggle');

      //Remove button from toolbar if not enabled in wysiwyg profile config and not pdw_toggle (Kitchen Sink)
      foreach($first_row_buttons as $button) {
        if (!in_array($button, $enabled_buttons) && $button != 'pdw_toggle') {
          unset($first_row_buttons[array_search($button, $first_row_buttons)]);
        }
      }
      $settings['theme_advanced_buttons1'] = implode(",", $first_row_buttons);
    }

    //Desired second row buttons. Include all defaults from panopoly_wysiwyg.module.
    $second_row_buttons = array('formatselect', '|', 'underline', '|', 'justifyfull', '|', 'forecolor', '|', 'pastetext', 'pasteword', 'removeformat', '|', 'charmap', '|', 'outdent', 'indent', '|', 'undo', 'redo');

    //Remove button from toolbar if not enabled in wysiwyg profile config and not formatselect (Block Format)
    foreach($second_row_buttons as $button) {
      if (!in_array($button, $enabled_buttons) && $button != 'formatselect') {
        unset($second_row_buttons[array_search($button, $second_row_buttons)]);
      }
    }
    $settings['theme_advanced_buttons2'] = implode(",", $second_row_buttons);

  }
}
